-- =============================================================================
-- Mercurio — Vessels
-- =============================================================================
-- Generated by scripts/mercurio-import/build_sql.py
-- Tenant: Mercurio (resolved by slug or fallback via LATERE vessel)
-- Idempotent: re-running keeps a single row per (tenant, vesselCode, code)
-- =============================================================================

BEGIN;

DO $$
DECLARE
  v_tenant_id text;
  v_user_id   text;

BEGIN
  -- Resolve tenant: prefer slug 'mercurio', fallback via LATERE vessel
  SELECT id INTO v_tenant_id FROM "Tenant" WHERE slug = 'mercurio' LIMIT 1;
  IF v_tenant_id IS NULL THEN
    SELECT t.id INTO v_tenant_id
    FROM "Tenant" t
    JOIN "Vessel" v ON v."tenantId" = t.id
    WHERE v.code IN ('LATERE','DONCHI','DON CHICUETO')
    ORDER BY v."createdAt" ASC
    LIMIT 1;
  END IF;
  IF v_tenant_id IS NULL THEN
    RAISE EXCEPTION 'Tenant Mercurio not found (no slug match and no LATERE/DONCHI vessel)';
  END IF;

  SELECT m."userId" INTO v_user_id
  FROM "TenantMembership" m
  WHERE m."tenantId" = v_tenant_id AND m.role = 'TENANT_ADMIN'
  ORDER BY m."createdAt" ASC LIMIT 1;
  IF v_user_id IS NULL THEN
    SELECT m."userId" INTO v_user_id
    FROM "TenantMembership" m
    WHERE m."tenantId" = v_tenant_id
    ORDER BY m."createdAt" ASC LIMIT 1;
  END IF;
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'No member found for Mercurio tenant';
  END IF;
  RAISE NOTICE 'Tenant: %, User: %', v_tenant_id, v_user_id;

  -- ── Insert vessels (idempotent via @@unique [tenantId, code]) ─────────────
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'DONCHI', 'DON CHICUETO', 'Remolcador / Empuje', '4768-RE', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'GLT001', 'GLT 001', 'Barcaza Tanque - Rake', '4246-BT', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'GLT007', 'GLT 007', 'Barcaza Tanque - Rake', '4321-BT', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'GLT008', 'GLT 008', 'Barcaza Tanque - Rake', '4322-BT', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'LATERE', 'LATERE', 'Remolcador / Empuje', '4497-RE', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'MAO01', 'MAO 01', 'Remolcador / Empuje', '4777-RE', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'MAO02', 'MAO 02', NULL, NULL, 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'MGT01', 'MGT 01', 'Barcaza Tanque - Rake', '4490-BT', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'MGT02', 'MGT 02', 'Barcaza Tanque - Rake', '4491-BT', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'MGT03', 'MGT 03', 'Barcaza Tanque - Rake', '4492-BT', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'MGT04', 'MGT 04', 'Barcaza Tanque - Rake', '4493-BT', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'MGT05', 'MGT 05', 'Barcaza Tanque - Box', '4494-BT', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'MGT06', 'MGT 06', 'Barcaza Tanque - Box', '4495-BT', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'MGT07', 'MGT 07', 'Barcaza Tanque - Box', '4496-BT', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'MGT08', 'MGT 08', 'Barcaza Tanque - Rake', '4513-BT', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'MGT09', 'MGT 09', 'Barcaza Tanque - Rake', '4518-BT', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'MGT10', 'MGT 10', 'Barcaza Tanque - Rake', '4715-BT', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'MGT11', 'MGT 11', 'Barcaza Tanque - Rake', '4716-BT', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'MGT12', 'MGT 12', 'Barcaza Tanque - Rake', '4717-BT', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'MGT13', 'MGT 13', 'Barcaza Tanque - Rake', '4718-BT', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'MGT14', 'MGT 14', 'Barcaza Tanque - Rake', '4719-BT', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'MGT15', 'MGT 15', 'Barcaza Tanque - Rake', '4720-BT', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'MGT16', 'MGT 16', NULL, NULL, 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'MGT17', 'MGT 17', NULL, NULL, 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'MGT18', 'MGT 18', NULL, NULL, 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'MGT19', 'MGT 19', 'Barcaza Tanque - Rake', '3484-BTQ', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'MGT20', 'MGT 20', NULL, NULL, 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'MGT21', 'MGT 21', NULL, NULL, 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'MGT22', 'MGT 22', 'Barcaza Tanque - Rake', '3485-BTQ', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'MGT23', 'MGT 23', 'Barcaza Tanque - Rake', '3514-BTQ', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'MGT24', 'MGT 24', NULL, NULL, 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'MGT25', 'MGT 25', 'Barcaza Tanque - Box', '3516-BTQ', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'MGT26', 'MGT 26', 'Barcaza Tanque - Box', '3534-BTQ', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'MGT27', 'MGT 27', 'Barcaza Tanque - Box', '3535-BTQ', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'YERUTI3', 'YERUTI III', NULL, NULL, 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'YT001', 'YT 001', NULL, NULL, 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'YT004', 'YT 004', NULL, NULL, 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'YT005', 'YT 005', 'Barcaza Tanque - Rake', '3907-BT', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'YT007', 'YT 007', 'Barcaza Tanque - Rake', '4184-BT', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'YT010', 'YT 010', 'Barcaza Tanque - Box', '4238-BT', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'YT011', 'YT 011', 'Barcaza Tanque - Box', NULL, 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'YT012', 'YT 012', 'Barcaza Tanque - Box', '4275-BT', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'YT013', 'YT 013', 'Barcaza Tanque - Box', '4320-BT', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'YT015', 'YT 015', 'Barcaza Tanque - Rake', '4350-BT', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'YT022', 'YT 022', 'Barcaza Tanque - Rake', '4698-BT', 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;

  RAISE NOTICE 'Vessels processed';
END $$;

SELECT COUNT(*) AS vessels_active
FROM "Vessel" v
JOIN "Tenant" t ON t.id = v."tenantId"
WHERE t.slug = 'mercurio' AND v.status = 'ACTIVE';

COMMIT;
