-- =============================================================================
-- Mercurio — DONCHI Sistemas (parent assets)
-- =============================================================================
-- Generated by scripts/mercurio-import/build_sql.py
-- Tenant: Mercurio (resolved by slug or fallback via LATERE vessel)
-- Idempotent: re-running keeps a single row per (tenant, vesselCode, code)
-- =============================================================================

BEGIN;

DO $$
DECLARE
  v_tenant_id text;
  v_user_id   text;

BEGIN
  -- Resolve tenant: prefer slug 'mercurio', fallback via LATERE vessel
  SELECT id INTO v_tenant_id FROM "Tenant" WHERE slug = 'mercurio' LIMIT 1;
  IF v_tenant_id IS NULL THEN
    SELECT t.id INTO v_tenant_id
    FROM "Tenant" t
    JOIN "Vessel" v ON v."tenantId" = t.id
    WHERE v.code IN ('LATERE','DONCHI','DON CHICUETO')
    ORDER BY v."createdAt" ASC
    LIMIT 1;
  END IF;
  IF v_tenant_id IS NULL THEN
    RAISE EXCEPTION 'Tenant Mercurio not found (no slug match and no LATERE/DONCHI vessel)';
  END IF;

  SELECT m."userId" INTO v_user_id
  FROM "TenantMembership" m
  WHERE m."tenantId" = v_tenant_id AND m.role = 'TENANT_ADMIN'
  ORDER BY m."createdAt" ASC LIMIT 1;
  IF v_user_id IS NULL THEN
    SELECT m."userId" INTO v_user_id
    FROM "TenantMembership" m
    WHERE m."tenantId" = v_tenant_id
    ORDER BY m."createdAt" ASC LIMIT 1;
  END IF;
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'No member found for Mercurio tenant';
  END IF;
  RAISE NOTICE 'Tenant: %, User: %', v_tenant_id, v_user_id;

  -- ── Insert system assets (parents). Each is a 'bucket' with criticality + safety set.

  -- DONCHI
  INSERT INTO "Asset" (id, "tenantId", "vesselCode", "assetCode", name, criticality, status, "isSafetyCritical", "trackDailyReport", "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'DONCHI', 'DONCHI-SYS-AIR', 'Compresores y Botellones de Aire', 'B', 'OPERATIONAL', false, false, NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", "vesselCode", "assetCode") DO NOTHING;
  INSERT INTO "Asset" (id, "tenantId", "vesselCode", "assetCode", name, criticality, status, "isSafetyCritical", "trackDailyReport", "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'DONCHI', 'DONCHI-SYS-ALT', 'Alternadores', 'A', 'OPERATIONAL', false, false, NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", "vesselCode", "assetCode") DO NOTHING;
  INSERT INTO "Asset" (id, "tenantId", "vesselCode", "assetCode", name, criticality, status, "isSafetyCritical", "trackDailyReport", "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'DONCHI', 'DONCHI-SYS-AUX-01', 'Motor Auxiliar N°1 (Babor)', 'A', 'OPERATIONAL', true, false, NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", "vesselCode", "assetCode") DO NOTHING;
  INSERT INTO "Asset" (id, "tenantId", "vesselCode", "assetCode", name, criticality, status, "isSafetyCritical", "trackDailyReport", "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'DONCHI', 'DONCHI-SYS-AUX-02', 'Motor Auxiliar N°2 (Estribor)', 'A', 'OPERATIONAL', true, false, NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", "vesselCode", "assetCode") DO NOTHING;
  INSERT INTO "Asset" (id, "tenantId", "vesselCode", "assetCode", name, criticality, status, "isSafetyCritical", "trackDailyReport", "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'DONCHI', 'DONCHI-SYS-AUX-03', 'Motor Auxiliar N°3 (Puerto)', 'A', 'OPERATIONAL', true, false, NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", "vesselCode", "assetCode") DO NOTHING;
  INSERT INTO "Asset" (id, "tenantId", "vesselCode", "assetCode", name, criticality, status, "isSafetyCritical", "trackDailyReport", "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'DONCHI', 'DONCHI-SYS-BBA', 'Bombas', 'B', 'OPERATIONAL', false, false, NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", "vesselCode", "assetCode") DO NOTHING;
  INSERT INTO "Asset" (id, "tenantId", "vesselCode", "assetCode", name, criticality, status, "isSafetyCritical", "trackDailyReport", "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'DONCHI', 'DONCHI-SYS-CAB', 'Cabrestante', 'B', 'OPERATIONAL', false, false, NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", "vesselCode", "assetCode") DO NOTHING;
  INSERT INTO "Asset" (id, "tenantId", "vesselCode", "assetCode", name, criticality, status, "isSafetyCritical", "trackDailyReport", "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'DONCHI', 'DONCHI-SYS-CAJ', 'Cajas Reductoras', 'A', 'OPERATIONAL', true, false, NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", "vesselCode", "assetCode") DO NOTHING;
  INSERT INTO "Asset" (id, "tenantId", "vesselCode", "assetCode", name, criticality, status, "isSafetyCritical", "trackDailyReport", "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'DONCHI', 'DONCHI-SYS-CLI', 'Aire Acondicionado Central', 'B', 'OPERATIONAL', false, false, NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", "vesselCode", "assetCode") DO NOTHING;
  INSERT INTO "Asset" (id, "tenantId", "vesselCode", "assetCode", name, criticality, status, "isSafetyCritical", "trackDailyReport", "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'DONCHI', 'DONCHI-SYS-EJE', 'Línea de Eje y Hélice', 'A', 'OPERATIONAL', true, false, NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", "vesselCode", "assetCode") DO NOTHING;
  INSERT INTO "Asset" (id, "tenantId", "vesselCode", "assetCode", name, criticality, status, "isSafetyCritical", "trackDailyReport", "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'DONCHI', 'DONCHI-SYS-ENG', 'Engrase', 'C', 'OPERATIONAL', false, false, NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", "vesselCode", "assetCode") DO NOTHING;
  INSERT INTO "Asset" (id, "tenantId", "vesselCode", "assetCode", name, criticality, status, "isSafetyCritical", "trackDailyReport", "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'DONCHI', 'DONCHI-SYS-EQC', 'Equipos Críticos', 'A', 'OPERATIONAL', true, false, NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", "vesselCode", "assetCode") DO NOTHING;
  INSERT INTO "Asset" (id, "tenantId", "vesselCode", "assetCode", name, criticality, status, "isSafetyCritical", "trackDailyReport", "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'DONCHI', 'DONCHI-SYS-GOB', 'Sistema de Gobierno', 'A', 'OPERATIONAL', true, false, NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", "vesselCode", "assetCode") DO NOTHING;
  INSERT INTO "Asset" (id, "tenantId", "vesselCode", "assetCode", name, criticality, status, "isSafetyCritical", "trackDailyReport", "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'DONCHI', 'DONCHI-SYS-HID', 'Central Hidráulica', 'B', 'OPERATIONAL', false, false, NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", "vesselCode", "assetCode") DO NOTHING;
  INSERT INTO "Asset" (id, "tenantId", "vesselCode", "assetCode", name, criticality, status, "isSafetyCritical", "trackDailyReport", "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'DONCHI', 'DONCHI-SYS-LAN-01', 'Motor Lancha de Trabajo 1', 'B', 'OPERATIONAL', false, false, NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", "vesselCode", "assetCode") DO NOTHING;
  INSERT INTO "Asset" (id, "tenantId", "vesselCode", "assetCode", name, criticality, status, "isSafetyCritical", "trackDailyReport", "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'DONCHI', 'DONCHI-SYS-PROP-BB', 'Sistema de Propulsión — Babor', 'A', 'OPERATIONAL', true, false, NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", "vesselCode", "assetCode") DO NOTHING;
  INSERT INTO "Asset" (id, "tenantId", "vesselCode", "assetCode", name, criticality, status, "isSafetyCritical", "trackDailyReport", "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'DONCHI', 'DONCHI-SYS-PROP-EB', 'Sistema de Propulsión — Estribor', 'A', 'OPERATIONAL', true, false, NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", "vesselCode", "assetCode") DO NOTHING;
  INSERT INTO "Asset" (id, "tenantId", "vesselCode", "assetCode", name, criticality, status, "isSafetyCritical", "trackDailyReport", "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'DONCHI', 'DONCHI-SYS-TER', 'Termotanques', 'C', 'OPERATIONAL', false, false, NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", "vesselCode", "assetCode") DO NOTHING;
  INSERT INTO "Asset" (id, "tenantId", "vesselCode", "assetCode", name, criticality, status, "isSafetyCritical", "trackDailyReport", "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, 'DONCHI', 'DONCHI-SYS-TOM', 'Tomas de Mar', 'B', 'OPERATIONAL', false, false, NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", "vesselCode", "assetCode") DO NOTHING;

  RAISE NOTICE 'System (parent) assets processed';
END $$;

COMMIT;
