#!/usr/bin/env python3
"""
Generate idempotent SQL scripts for Mercurio tenant import.

Reads:  scripts/mercurio-import/normalized/all.json
Writes: scripts/mercurio-import/sql/*.sql

Strategy:
  - Each Excel sheet (PMP system) -> 1 parent Asset (system bucket).
  - Each "equipment" mentioned in tasks -> 1 child Asset (parentAssetId = system).
  - Each (vessel, system, frequency, isInspection) -> 1 MaintenancePlan.
    title       = "[<System>] Inspección periódica <label>"  or  "[<System>] Mantenimiento <label>"
    description = bulleted list of items: "<equipment> — <task>"
    assetId     = system parent asset id (so the plan covers all equipment under it).
  - Spares -> 1 Spare per (motor, partNumber). linkedAssetId not set (would require equipment per vessel).
  - Certificates -> 1 Certificate per (vessel, name + expiryDate).
"""
import json
import re
from pathlib import Path
from collections import defaultdict

ROOT = Path(r"c:\NPMS\GPMS\scripts\mercurio-import")
OUT = ROOT / "sql"
OUT.mkdir(parents=True, exist_ok=True)

with open(ROOT / "normalized" / "all.json", encoding="utf-8") as f:
    DATA = json.load(f)


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────
def sql_str(s):
    """Quote string for SQL, handling None and escaping single quotes."""
    if s is None or s == "":
        return "NULL"
    s = str(s).replace("\x00", "").replace("\r", "")
    s = s.replace("'", "''")
    return f"'{s}'"


def sql_int(n):
    if n is None or n == "":
        return "NULL"
    try:
        return str(int(n))
    except (ValueError, TypeError):
        return "NULL"


def sql_float(n):
    if n is None or n == "":
        return "NULL"
    try:
        return str(float(n))
    except (ValueError, TypeError):
        return "NULL"


def sql_date(s):
    """Convert datestring to SQL date, or NULL if not parseable."""
    if not s:
        return "NULL"
    if isinstance(s, str):
        m = re.match(r"^(\d{4})-(\d{2})-(\d{2})", s)
        if m:
            return f"'{m.group(1)}-{m.group(2)}-{m.group(3)}'"
    return "NULL"


def normalize_text(s):
    if s is None:
        return ""
    return re.sub(r"\s+", " ", str(s).strip())


def vessel_code_for(name):
    """Convert display name to vessel code (uppercase, no spaces, special-cases)."""
    if not name:
        return None
    n = name.upper().strip()
    # Special cases
    if n == "DON CHICUETO":          return "DONCHI"
    if n == "DON CHICHUETO":         return "DONCHI"  # typo variant
    # Roman numeral suffix → arabic (cleaner)
    n = re.sub(r"\s+VIII\s*$", "8", n)
    n = re.sub(r"\s+VII\s*$",  "7", n)
    n = re.sub(r"\s+VI\s*$",   "6", n)
    n = re.sub(r"\s+IV\s*$",   "4", n)
    n = re.sub(r"\s+III\s*$",  "3", n)
    n = re.sub(r"\s+II\s*$",   "2", n)
    n = re.sub(r"\s+IX\s*$",   "9", n)
    n = re.sub(r"\s+X\s*$",    "10", n)
    n = re.sub(r"\s+V\s*$",    "5", n)
    n = re.sub(r"\s+I\s*$",    "1", n)
    return re.sub(r"\s+", "", n)


# ─────────────────────────────────────────────────────────────────────────────
# Header used in all SQL scripts (resolves tenant + user + helper functions)
# ─────────────────────────────────────────────────────────────────────────────
HEADER = """-- =============================================================================
-- {title}
-- =============================================================================
-- Generated by scripts/mercurio-import/build_sql.py
-- Tenant: Mercurio (resolved by slug or fallback via LATERE vessel)
-- Idempotent: re-running keeps a single row per (tenant, vesselCode, code)
-- =============================================================================

BEGIN;

DO $$
DECLARE
  v_tenant_id text;
  v_user_id   text;
"""


def tenant_resolver(extra_decls=""):
    """Returns the SQL block that resolves tenant + user."""
    return f"""{extra_decls}
BEGIN
  -- Resolve tenant: prefer slug 'mercurio', fallback via LATERE vessel
  SELECT id INTO v_tenant_id FROM "Tenant" WHERE slug = 'mercurio' LIMIT 1;
  IF v_tenant_id IS NULL THEN
    SELECT t.id INTO v_tenant_id
    FROM "Tenant" t
    JOIN "Vessel" v ON v."tenantId" = t.id
    WHERE v.code IN ('LATERE','DONCHI','DON CHICUETO')
    ORDER BY v."createdAt" ASC
    LIMIT 1;
  END IF;
  IF v_tenant_id IS NULL THEN
    RAISE EXCEPTION 'Tenant Mercurio not found (no slug match and no LATERE/DONCHI vessel)';
  END IF;

  SELECT m."userId" INTO v_user_id
  FROM "TenantMembership" m
  WHERE m."tenantId" = v_tenant_id AND m.role = 'TENANT_ADMIN'
  ORDER BY m."createdAt" ASC LIMIT 1;
  IF v_user_id IS NULL THEN
    SELECT m."userId" INTO v_user_id
    FROM "TenantMembership" m
    WHERE m."tenantId" = v_tenant_id
    ORDER BY m."createdAt" ASC LIMIT 1;
  END IF;
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'No member found for Mercurio tenant';
  END IF;
  RAISE NOTICE 'Tenant: %, User: %', v_tenant_id, v_user_id;
"""


# =============================================================================
# 00 — VESSELS
# =============================================================================
def build_vessels_sql():
    # Use vessels from FLOTA + cross-reference certificates to capture YERUTI etc.
    vessels = {}
    for v in DATA["vessels"]:
        code = vessel_code_for(v["name"])
        if not code:
            continue
        vessels[code] = {
            "code":   code,
            "name":   v["name"],
            "type":   v.get("tipo"),
            "registration": v.get("matricula"),
        }

    # Add vessels from certificates not in flota
    cert_vessels = set()
    for c in DATA["certificates"]:
        cv = vessel_code_for(c["vessel"])
        if cv and cv not in vessels:
            cert_vessels.add((cv, c["vessel"]))
    for code, name in cert_vessels:
        vessels[code] = {"code": code, "name": name, "type": None, "registration": None}

    sql = HEADER.format(title="Mercurio — Vessels")
    sql += tenant_resolver()
    sql += "\n  -- ── Insert vessels (idempotent via @@unique [tenantId, code]) ─────────────\n"
    for code in sorted(vessels.keys()):
        v = vessels[code]
        sql += f"""  INSERT INTO "Vessel" (id, "tenantId", code, name, "vesselType", registration, status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, {sql_str(v['code'])}, {sql_str(v['name'])}, {sql_str(v['type'])}, {sql_str(v['registration'])}, 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", code) DO NOTHING;
"""
    sql += "\n  RAISE NOTICE 'Vessels processed';\n"
    sql += "END $$;\n\n"
    sql += """SELECT COUNT(*) AS vessels_active
FROM "Vessel" v
JOIN "Tenant" t ON t.id = v."tenantId"
WHERE t.slug = 'mercurio' AND v.status = 'ACTIVE';

COMMIT;
"""
    (OUT / "00-mercurio-vessels.sql").write_text(sql, encoding="utf-8")
    print(f"  -> 00-mercurio-vessels.sql  ({len(vessels)} vessels)")
    return vessels


# =============================================================================
# Helper: group tasks into plans
# =============================================================================
FREQ_LABEL = {
    1:    "Mensual",
    2:    "Bimestral",
    3:    "Trimestral",
    4:    "Cuatrimestral",
    6:    "Semestral",
    12:   "Anual",
    18:   "Cada 18 meses",
    24:   "Bianual",
    36:   "Cada 3 años",
    60:   "Cada 5 años",
    72:   "Cada 6 años / Dique seco",
    96:   "Cada 8 años",
}


def freq_label(trigger, hours, months):
    if trigger == "HOURS":
        return f"Cada {hours}h"
    if trigger == "MONTHS":
        if months in FREQ_LABEL:
            return FREQ_LABEL[months]
        return f"Cada {months} meses"
    return "—"


def freq_key(trigger, hours, months):
    if trigger == "HOURS":
        return f"{hours}H"
    if trigger == "MONTHS":
        return f"{months}M"
    return ""


def freq_code_short(trigger, hours, months):
    """Short code for taskCode suffix."""
    if trigger == "HOURS":
        return f"{hours}H"
    if trigger == "MONTHS":
        return f"{months}M"
    return "X"


def group_plans(tasks):
    """Group tasks by (vesselCode, systemCode, freq_key, isInspection).

    Returns: dict[(vc, sc, fkey, isInsp)] -> {
        "vesselCode", "systemCode", "systemName",
        "trigger", "hours", "months", "label", "isInspection",
        "tasks": [task...]   (raw task dicts, for description),
    }
    """
    groups = {}
    for t in tasks:
        fk = freq_key(t["trigger"], t["hours"], t["months"])
        key = (t["vesselCode"], t["systemCode"], fk, t["isInspection"])
        g = groups.get(key)
        if g is None:
            g = {
                "vesselCode":   t["vesselCode"],
                "systemCode":   t["systemCode"],
                "systemName":   t["systemName"],
                "trigger":      t["trigger"],
                "hours":        t["hours"],
                "months":       t["months"],
                "label":        freq_label(t["trigger"], t["hours"], t["months"]),
                "isInspection": t["isInspection"],
                "tasks":        [],
            }
            groups[key] = g
        g["tasks"].append(t)
    return groups


def build_description(group):
    """Build a bulleted description from grouped tasks."""
    lines = []
    seen = set()
    for t in group["tasks"]:
        equip = t["equipment"] or "—"
        task = t["task"]
        ident = (equip.lower(), task.lower())
        if ident in seen:
            continue
        seen.add(ident)
        lines.append(f"• {equip} — {task}")
    return "\n".join(lines)


# =============================================================================
# 01-04 — LATERE / DONCHI ASSETS + PLANS
# =============================================================================
SYSTEM_NAMES = {
    "PROP-EB":  "Sistema de Propulsión — Estribor",
    "PROP-BB":  "Sistema de Propulsión — Babor",
    "PROP-EBC": "Sistema de Propulsión — Estribor Centro",
    "PROP-BBC": "Sistema de Propulsión — Babor Centro",
    "AUX-01":   "Motor Auxiliar N°1 (Babor)",
    "AUX-02":   "Motor Auxiliar N°2 (Estribor)",
    "AUX-03":   "Motor Auxiliar N°3 (Puerto)",
    "CAJ":      "Cajas Reductoras",
    "ALT":      "Alternadores",
    "BBA":      "Bombas",
    "AIR":      "Compresores y Botellones de Aire",
    "GOB":      "Sistema de Gobierno",
    "EJE":      "Línea de Eje y Hélice",
    "CAB":      "Cabrestante",
    "LAN-01":   "Motor Lancha de Trabajo 1",
    "LAN-02":   "Motor Lancha de Trabajo 2",
    "SEP":      "Separador de Sentina",
    "PUR":      "Purificadora",
    "HID":      "Central Hidráulica",
    "ENG":      "Engrase",
    "EQC":      "Equipos Críticos",
    "SEW":      "Sewage / Tratamiento de Efluentes",
    "TOM":      "Tomas de Mar",
    "TER":      "Termotanques",
    "CLI":      "Aire Acondicionado Central",
    # Barcazas-only
    "TNQ":      "Tanques de Carga",
    "CIN":      "Lucha Contraincendio",
    "CRG":      "Sistema de Cargamento",
    "EMG":      "Paradas de Emergencia",
    "CUB":      "Equipamiento de Cubierta",
    "ALR":      "Alarmas de Nivel",
    "CSC":      "Casco",
    "INS":      "Instrumentación",
    "ELE":      "Sistema Eléctrico",
    "NAV":      "Navegación",
    "OTROS":    "Otros",
    # Generic for barcazas (no Bb/Eb split)
    "PROP":     "Motor Principal",
}


SYSTEM_CRITICALITY = {
    "PROP-EB":  ("A", True),
    "PROP-BB":  ("A", True),
    "PROP-EBC": ("A", True),
    "PROP-BBC": ("A", True),
    "AUX-01":   ("A", True),
    "AUX-02":   ("A", True),
    "AUX-03":   ("A", True),
    "CAJ":      ("A", True),
    "ALT":      ("A", False),
    "BBA":      ("B", False),
    "AIR":      ("B", False),
    "GOB":      ("A", True),
    "EJE":      ("A", True),
    "CAB":      ("B", False),
    "LAN-01":   ("B", False),
    "LAN-02":   ("B", False),
    "SEP":      ("B", False),
    "PUR":      ("A", False),
    "HID":      ("B", False),
    "ENG":      ("C", False),
    "EQC":      ("A", True),
    "SEW":      ("B", False),
    "TOM":      ("B", False),
    "TER":      ("C", False),
    "CLI":      ("B", False),
    "TNQ":      ("A", True),
    "CIN":      ("A", True),
    "CRG":      ("A", True),
    "EMG":      ("A", True),
    "CUB":      ("B", False),
    "ALR":      ("A", False),
    "CSC":      ("A", False),
    "INS":      ("B", False),
    "ELE":      ("A", True),
    "NAV":      ("A", True),
    "OTROS":    ("B", False),
    "PROP":     ("A", True),
}


def system_asset_code(vessel_code, system_code):
    return f"{vessel_code}-SYS-{system_code}"


def write_assets_sql(label, vessels_with_systems, output_filename):
    """vessels_with_systems = dict[vessel_code] -> set of system_codes used."""
    sql = HEADER.format(title=label)
    sql += tenant_resolver()
    sql += "\n  -- ── Insert system assets (parents). Each is a 'bucket' with criticality + safety set.\n"
    for vc in sorted(vessels_with_systems.keys()):
        sql += f"\n  -- {vc}\n"
        for sc in sorted(vessels_with_systems[vc]):
            asset_code = system_asset_code(vc, sc)
            name       = SYSTEM_NAMES.get(sc, sc)
            crit, safe = SYSTEM_CRITICALITY.get(sc, ("B", False))
            sql += f"""  INSERT INTO "Asset" (id, "tenantId", "vesselCode", "assetCode", name, criticality, status, "isSafetyCritical", "trackDailyReport", "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, {sql_str(vc)}, {sql_str(asset_code)}, {sql_str(name)}, '{crit}', 'OPERATIONAL', {str(safe).lower()}, false, NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", "vesselCode", "assetCode") DO NOTHING;
"""

    sql += "\n  RAISE NOTICE 'System (parent) assets processed';\n"
    sql += "END $$;\n\nCOMMIT;\n"
    (OUT / output_filename).write_text(sql, encoding="utf-8")


def write_plans_sql(label, plans, output_filename):
    sql = HEADER.format(title=label)
    sql += tenant_resolver("  v_asset_id  text;\n  v_count     integer := 0;")
    sql += "\n  -- ── Insert MaintenancePlans grouped by (vessel, system, frequency, type) ──\n"

    by_vessel = defaultdict(list)
    for p in plans:
        by_vessel[p["vesselCode"]].append(p)

    for vc in sorted(by_vessel.keys()):
        sql += f"\n  -- ── Vessel {vc} ──\n"
        for p in by_vessel[vc]:
            sc = p["systemCode"]
            asset_code = system_asset_code(vc, sc)
            sys_label = SYSTEM_NAMES.get(sc, sc)
            kind = "Inspección" if p["isInspection"] else "Mantenimiento"
            title = f"[{sys_label}] {kind} {p['label']}"
            insp_suffix = "I" if p["isInspection"] else "M"
            task_code = f"{vc}-{sc}-{freq_code_short(p['trigger'], p['hours'], p['months'])}-{insp_suffix}"
            description = build_description(p)
            trigger_enum = "HOURS" if p["trigger"] == "HOURS" else "MONTHS"
            task_type    = "INSPECTION" if p["isInspection"] else "MAINTENANCE"

            sql += f"""  -- {title}
  SELECT id INTO v_asset_id FROM "Asset"
   WHERE "tenantId" = v_tenant_id AND "vesselCode" = {sql_str(vc)} AND "assetCode" = {sql_str(asset_code)} AND "deletedAt" IS NULL LIMIT 1;
  IF v_asset_id IS NOT NULL THEN
    INSERT INTO "MaintenancePlan" (
      id, "tenantId", "vesselCode", "assetId", "taskCode", title, description,
      "triggerType", "frequencyHours", "frequencyMonths", "taskType", status, "executionStatus",
      "createdAt", "createdByUserId", "updatedAt", "updatedByUserId"
    )
    VALUES (
      gen_random_uuid()::text, v_tenant_id, {sql_str(vc)}, v_asset_id, {sql_str(task_code)},
      {sql_str(title)}, {sql_str(description)},
      CAST({sql_str(trigger_enum)} AS "MaintenancePlanTrigger"),
      {sql_float(p["hours"])}, {sql_int(p["months"])},
      CAST({sql_str(task_type)} AS "TaskType"),
      CAST('ACTIVE' AS "MaintenancePlanStatus"),
      CAST('FUTURE' AS "ExecutionStatus"),
      NOW(), v_user_id, NOW(), v_user_id
    )
    ON CONFLICT ("tenantId", "vesselCode", "taskCode") DO NOTHING;
    v_count := v_count + 1;
  END IF;
"""

    sql += "\n  RAISE NOTICE 'MaintenancePlans processed: %', v_count;\n"
    sql += "END $$;\n\nCOMMIT;\n"
    (OUT / output_filename).write_text(sql, encoding="utf-8")


def build_latere():
    tasks = [t for t in DATA["tasks"] if t["vesselCode"] == "LATERE"]
    systems = sorted({t["systemCode"] for t in tasks})
    write_assets_sql(
        "Mercurio — LATERE Sistemas (parent assets)",
        {"LATERE": systems},
        "01-mercurio-latere-assets.sql",
    )
    plans = list(group_plans(tasks).values())
    write_plans_sql(
        "Mercurio — LATERE Planes de Mantenimiento",
        plans,
        "02-mercurio-latere-plans.sql",
    )
    print(f"  -> 01-mercurio-latere-assets.sql  ({len(systems)} systems)")
    print(f"  -> 02-mercurio-latere-plans.sql   ({len(plans)} plans, from {len(tasks)} tasks)")


def build_donchi():
    tasks = [t for t in DATA["tasks"] if t["vesselCode"] == "DONCHI"]
    systems = sorted({t["systemCode"] for t in tasks})
    write_assets_sql(
        "Mercurio — DONCHI Sistemas (parent assets)",
        {"DONCHI": systems},
        "03-mercurio-donchi-assets.sql",
    )
    plans = list(group_plans(tasks).values())
    write_plans_sql(
        "Mercurio — DONCHI Planes de Mantenimiento",
        plans,
        "04-mercurio-donchi-plans.sql",
    )
    print(f"  -> 03-mercurio-donchi-assets.sql  ({len(systems)} systems)")
    print(f"  -> 04-mercurio-donchi-plans.sql   ({len(plans)} plans, from {len(tasks)} tasks)")


def build_barcazas():
    tasks = DATA["barcazasTasks"]
    by_vessel = defaultdict(set)
    for t in tasks:
        by_vessel[t["vesselCode"]].add(t["systemCode"])
    write_assets_sql(
        "Mercurio — Barcazas (MGT/GLT/YT) Sistemas",
        dict(by_vessel),
        "05-mercurio-barcazas-assets.sql",
    )
    plans = list(group_plans(tasks).values())
    write_plans_sql(
        "Mercurio — Barcazas Planes de Mantenimiento",
        plans,
        "06-mercurio-barcazas-plans.sql",
    )
    total_vc = len(by_vessel)
    total_sys = sum(len(v) for v in by_vessel.values())
    print(f"  -> 05-mercurio-barcazas-assets.sql  ({total_vc} vessels, {total_sys} system rows)")
    print(f"  -> 06-mercurio-barcazas-plans.sql   ({len(plans)} plans, from {len(tasks)} tasks)")


# =============================================================================
# 07 — SPARES
# =============================================================================
MOTOR_VESSEL_MAP = {
    "CAT":             ["MGT10","MGT11","MGT12","MGT13","MGT14","MGT15","GLT001"],
    "JOHN DEERE":      ["MGT01","MGT02","MGT03","MGT04","MGT05","MGT06","MGT07","MGT08","MGT09",
                        "MGT16","MGT17","MGT18","MGT19","MGT20","MGT21","MGT22","MGT23","MGT24","MGT25","MGT26","MGT27"],
    "JOHN-DEERE-FULL": ["MGT01","MGT02","MGT03","MGT04","MGT05","MGT06","MGT07","MGT08","MGT09",
                        "MGT16","MGT17","MGT18","MGT19","MGT20","MGT21","MGT22","MGT23","MGT24","MGT25","MGT26","MGT27"],
    "MWM":             ["GLT007","GLT008"],
    "MWM-FULL":        ["GLT007","GLT008"],
    "MWM-EXT":         ["GLT007","GLT008"],
    "DETROIT":         ["YT005","YT010","YT012","YT013","YT015","YT022"],
    "DETROIT-FULL":    ["YT005","YT010","YT012","YT013","YT015","YT022"],
    "DETROIT-EXT":     ["YT005","YT010","YT012","YT013","YT015","YT022"],
    # Note: el Cummins de la lista (LF670, LFP815FN…) corresponde al motor
    # del YT 007. LATERE también tiene Cummins, pero modelos distintos
    # (K50/N855-DM/6BT5.9D) — no se asignan acá. Cuando se consigan los
    # part numbers reales se cargan en un seed específico.
    "CUMMINS":         ["YT007"],
}


def make_sku(motor, part):
    """Build a SKU: MOTOR-PARTNUMBER (sanitized)."""
    motor_short = motor.split()[0] if motor else "GEN"
    motor_short = re.sub(r"[^A-Z0-9]", "", motor_short.upper())[:4]
    part_clean = re.sub(r"[^A-Z0-9]", "", str(part).upper())[:20]
    return f"{motor_short}-{part_clean}"


def build_spares():
    sql = HEADER.format(title="Mercurio — Repuestos críticos")
    sql += tenant_resolver()
    sql += "\n  -- ── Insert spares per vessel (one row per vessel × spare). ────────────────\n"

    spares = DATA["spares"]
    seen = set()
    count = 0

    for sp in spares:
        motor = sp["motor"] or ""
        part  = sp["partNumber"] or ""
        name  = sp["name"] or ""
        if not part or not name:
            continue

        # Resolve which vessels this spare applies to
        vessels_for_spare = sp.get("vessels") or []
        if not vessels_for_spare:
            vessels_for_spare = MOTOR_VESSEL_MAP.get(motor.upper(), [])
        if not vessels_for_spare:
            continue

        sku = make_sku(motor, part)
        crit = sp.get("criticality") or "B"
        min_qty = sp.get("minQty") or 0

        for vc in vessels_for_spare:
            ident = (vc, sku)
            if ident in seen:
                continue
            seen.add(ident)
            sql += f"""  INSERT INTO "Spare" (id, "tenantId", "vesselCode", sku, name, "manufacturerPartNumber", manufacturer, criticality, unit, "currentStock", "minStock", "reorderPoint", status, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, {sql_str(vc)}, {sql_str(sku)}, {sql_str(name)}, {sql_str(part)}, {sql_str(motor)}, '{crit}', 'UN', 0, {min_qty}, {min_qty}, 'ACTIVE', NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", "vesselCode", sku) DO NOTHING;
"""
            count += 1

    sql += f"\n  RAISE NOTICE 'Spares processed: ~{count} rows';\n"
    sql += "END $$;\n\nCOMMIT;\n"
    (OUT / "07-mercurio-spares.sql").write_text(sql, encoding="utf-8")
    print(f"  -> 07-mercurio-spares.sql  (~{count} spare-vessel rows)")


# =============================================================================
# 08 — CERTIFICATES
# =============================================================================
def parse_cert_date(s):
    """Parse cert dates: 'YYYY-MM-DD HH:MM:SS' format or 'Pendiente'/'Sin Vencimiento'."""
    if not s:
        return None
    if isinstance(s, str):
        s = s.strip()
        if s.lower() in ("pendiente", "sin vencimiento", ""):
            return None
        m = re.match(r"^(\d{4})-(\d{2})-(\d{2})", s)
        if m:
            return f"{m.group(1)}-{m.group(2)}-{m.group(3)}"
    return None


def build_certificates():
    sql = HEADER.format(title="Mercurio — Certificados")
    sql += tenant_resolver()
    sql += "\n  -- ── Insert certificates (only those with valid expiry date) ──────────────\n"

    count = 0
    skipped = 0
    seen = set()

    for c in DATA["certificates"]:
        vc = vessel_code_for(c["vessel"])
        name = normalize_text(c["name"])
        if not vc or not name:
            skipped += 1
            continue
        issue = parse_cert_date(c["issueDate"])
        expiry = parse_cert_date(c["expiryDate"])
        if not expiry:
            # Skip certs without expiry date (model requires it).
            skipped += 1
            continue
        if not issue:
            issue = expiry  # fallback
        # Stable cert code: vesselCode-name-expiry (truncate name)
        name_part = re.sub(r"[^A-Z0-9]", "", name.upper())[:30]
        cert_code = f"{vc}-{name_part}-{expiry.replace('-','')}"
        if cert_code in seen:
            continue
        seen.add(cert_code)
        issuer = c.get("issuer") or "—"
        manager = c.get("manager") or ""
        validity = c.get("validity") or ""
        notes_parts = []
        if manager: notes_parts.append(f"Gestiona: {manager}")
        if validity: notes_parts.append(f"Validez: {validity}")
        if c.get("notes"): notes_parts.append(c["notes"])
        notes = " | ".join(notes_parts)

        sql += f"""  INSERT INTO "Certificate" (id, "tenantId", "vesselCode", "certificateCode", name, "issuingAuthority", status, "issueDate", "expiryDate", notes, "createdAt", "createdByUserId", "updatedAt", "updatedByUserId")
  VALUES (gen_random_uuid()::text, v_tenant_id, {sql_str(vc)}, {sql_str(cert_code)}, {sql_str(name)}, {sql_str(issuer)}, 'ACTIVE', '{issue}'::timestamp, '{expiry}'::timestamp, {sql_str(notes)}, NOW(), v_user_id, NOW(), v_user_id)
  ON CONFLICT ("tenantId", "vesselCode", "certificateCode") DO NOTHING;
"""
        count += 1

    sql += f"\n  RAISE NOTICE 'Certificates processed: {count} (skipped: {skipped})';\n"
    sql += "END $$;\n\nCOMMIT;\n"
    (OUT / "08-mercurio-certificates.sql").write_text(sql, encoding="utf-8")
    print(f"  -> 08-mercurio-certificates.sql  ({count} certificates, {skipped} skipped)")


def main():
    print("Building SQL scripts for Mercurio import...")
    build_vessels_sql()
    build_latere()
    build_donchi()
    build_barcazas()
    build_spares()
    build_certificates()
    print("\n=== DONE ===")
    for p in sorted(OUT.glob("*.sql")):
        print(f"  {p.name}  ({p.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
