import ExcelJS from "exceljs";
import type { ExcelModule } from "./excel-permissions";

interface ColumnDef {
  key: string;
  header: string;
  required: boolean;
  width?: number;
}

const MODULE_COLUMNS: Record<ExcelModule, ColumnDef[]> = {
  vessels: [
    { key: "code",               header: "code *",               required: true,  width: 20 },
    { key: "name",               header: "name",                 required: false, width: 30 },
    { key: "owner",              header: "owner",                required: false, width: 30 },
    { key: "vesselType",         header: "vesselType",           required: false, width: 28 },
    { key: "imo",                header: "imo",                  required: false, width: 18 },
    { key: "registration",       header: "registration",         required: false, width: 18 },
    { key: "powerHp",            header: "powerHp",              required: false, width: 14 },
    { key: "dwtTons",            header: "dwtTons",              required: false, width: 14 },
    { key: "lengthM",            header: "lengthM",              required: false, width: 12 },
    { key: "beamM",              header: "beamM",                required: false, width: 12 },
    { key: "depthM",             header: "depthM",               required: false, width: 12 },
    { key: "trnTn",              header: "trnTn",                required: false, width: 12 },
    { key: "trbTn",              header: "trbTn",                required: false, width: 12 },
    { key: "buildYear",          header: "buildYear",            required: false, width: 12 },
    { key: "buildCountry",       header: "buildCountry",         required: false, width: 20 },
    { key: "incorporationDate",  header: "incorporationDate",    required: false, width: 18 },
    { key: "incorporationType",  header: "incorporationType",    required: false, width: 20 },
    { key: "status",             header: "status",               required: false, width: 15 },
  ],
  assets: [
    { key: "vesselCode",       header: "vesselCode *",       required: true,  width: 20 },
    { key: "sfiCode",          header: "sfiCode *",          required: true,  width: 20 },
    { key: "assetCode",        header: "assetCode *",        required: true,  width: 20 },
    { key: "name",             header: "name",               required: false, width: 30 },
    { key: "criticality",      header: "criticality",        required: false, width: 15 },
    { key: "status",           header: "status",             required: false, width: 20 },
    { key: "manufacturer",     header: "manufacturer",       required: false, width: 25 },
    { key: "model",            header: "model",              required: false, width: 20 },
    { key: "serialNumber",     header: "serialNumber",       required: false, width: 25 },
    { key: "installationDate",  header: "installationDate",   required: false, width: 20 },
    { key: "lastOverhaulDate",  header: "lastOverhaulDate",   required: false, width: 20 },
    { key: "replacementDate",   header: "replacementDate",    required: false, width: 20 },
    { key: "trackDailyReport",  header: "trackDailyReport",   required: false, width: 18 },
  ],
  maintenance_plans: [
    { key: "vesselCode",          header: "vesselCode *",         required: true,  width: 20 },
    { key: "assetCode",           header: "assetCode",            required: false, width: 22 },
    { key: "sfiGroupNumber",      header: "sfiGroupNumber",       required: false, width: 16 },
    { key: "sfiCode",             header: "sfiCode",              required: false, width: 20 },
    { key: "taskCode",            header: "taskCode *",           required: true,  width: 20 },
    { key: "title",               header: "title *",              required: true,  width: 40 },
    { key: "description",         header: "description",          required: false, width: 50 },
    { key: "taskType",            header: "taskType",             required: false, width: 18 },
    { key: "triggerType",         header: "triggerType",          required: false, width: 18 },
    { key: "frequencyMonths",     header: "frequencyMonths",      required: false, width: 18 },
    { key: "frequencyHours",      header: "frequencyHours",       required: false, width: 18 },
    { key: "estimatedHours",      header: "estimatedHours",       required: false, width: 16 },
    { key: "responsible",         header: "responsible",          required: false, width: 25 },
    { key: "acceptanceCriteria",  header: "acceptanceCriteria",   required: false, width: 50 },
    { key: "loto",                header: "loto",                 required: false, width: 40 },
    { key: "riskLevel",           header: "riskLevel",            required: false, width: 14 },
    { key: "riskAnalysisResult",  header: "riskAnalysisResult",   required: false, width: 50 },
    { key: "consequenceCategory", header: "consequenceCategory",  required: false, width: 22 },
    { key: "consequenceRationale", header: "consequenceRationale", required: false, width: 50 },
    { key: "triggerResultMode",   header: "triggerResultMode",    required: false, width: 22 },
    { key: "windowMode",          header: "windowMode",           required: false, width: 15 },
    { key: "windowLeadDays",      header: "windowLeadDays",       required: false, width: 16 },
    { key: "windowLeadHours",     header: "windowLeadHours",      required: false, width: 17 },
    { key: "lastExecutionDate",   header: "lastExecutionDate",    required: false, width: 20 },
    { key: "nextDueDate",         header: "nextDueDate",          required: false, width: 18 },
    { key: "lastExecutionHours",  header: "lastExecutionHours",   required: false, width: 20 },
    { key: "nextDueHours",        header: "nextDueHours",         required: false, width: 16 },
    { key: "checklistTemplate",   header: "checklistTemplate",    required: false, width: 25 },
    { key: "samplingKind",        header: "samplingKind",         required: false, width: 18 },
    { key: "samplingFluidType",   header: "samplingFluidType",    required: false, width: 20 },
    { key: "status",              header: "status",               required: false, width: 18 },
  ],
  work_orders: [
    { key: "workOrderCode",  header: "workOrderCode",  required: false, width: 22 },
    { key: "vesselCode",     header: "vesselCode",     required: false, width: 18 },
    { key: "type",           header: "type",           required: false, width: 20 },
    { key: "status",         header: "status",         required: false, width: 18 },
    { key: "priority",       header: "priority",       required: false, width: 14 },
    { key: "criticality",    header: "criticality",    required: false, width: 14 },
    { key: "title",          header: "title",          required: false, width: 40 },
    { key: "openDate",       header: "openDate",       required: false, width: 18 },
    { key: "dueDate",        header: "dueDate",        required: false, width: 18 },
    { key: "startDate",      header: "startDate",      required: false, width: 18 },
    { key: "completedDate",  header: "completedDate",  required: false, width: 18 },
    { key: "estimatedHours", header: "estimatedHours", required: false, width: 16 },
    { key: "description",    header: "description",    required: false, width: 50 },
  ],
  spares: [
    { key: "vesselCode",             header: "vesselCode *",           required: true,  width: 20 },
    { key: "sku",                    header: "sku *",                  required: true,  width: 20 },
    { key: "name",                   header: "name",                   required: false, width: 30 },
    { key: "category",               header: "category",               required: false, width: 20 },
    { key: "criticality",            header: "criticality",            required: false, width: 15 },
    { key: "status",                 header: "status",                 required: false, width: 15 },
    { key: "manufacturer",           header: "manufacturer",           required: false, width: 25 },
    { key: "model",                  header: "model",                  required: false, width: 20 },
    { key: "internalPartNumber",     header: "internalPartNumber",     required: false, width: 25 },
    { key: "manufacturerPartNumber", header: "manufacturerPartNumber", required: false, width: 28 },
    { key: "unit",                   header: "unit",                   required: false, width: 12 },
    { key: "currentStock",           header: "currentStock",           required: false, width: 14 },
    { key: "minStock",               header: "minStock",               required: false, width: 12 },
    { key: "reorderPoint",           header: "reorderPoint",           required: false, width: 15 },
    { key: "targetStock",            header: "targetStock",            required: false, width: 14 },
    { key: "location",               header: "location",               required: false, width: 20 },
    { key: "sfiCode",                header: "sfiCode",                required: false, width: 18 },
    { key: "leadTimeDays",           header: "leadTimeDays",           required: false, width: 14 },
    { key: "longDescription",        header: "longDescription",        required: false, width: 50 },
  ],
  providers: [
    { key: "vesselCode",    header: "vesselCode *",   required: true,  width: 20 },
    { key: "providerCode",  header: "providerCode *", required: true,  width: 20 },
    { key: "name",          header: "name",           required: false, width: 30 },
    { key: "category",      header: "category",       required: false, width: 20 },
    { key: "status",        header: "status",         required: false, width: 15 },
    { key: "contactName",   header: "contactName",    required: false, width: 25 },
    { key: "contactEmail",  header: "contactEmail",   required: false, width: 30 },
    { key: "contactPhone",  header: "contactPhone",   required: false, width: 20 },
    { key: "location",      header: "location",       required: false, width: 25 },
  ],
  certificates: [
    { key: "vesselCode",          header: "vesselCode *",       required: true,  width: 20 },
    { key: "certificateCode",     header: "certificateCode *",  required: true,  width: 25 },
    { key: "name",                header: "name",               required: false, width: 35 },
    { key: "issuingAuthority",    header: "issuingAuthority",   required: false, width: 30 },
    { key: "status",              header: "status",             required: false, width: 18 },
    { key: "issueDate",           header: "issueDate",          required: false, width: 18 },
    { key: "expiryDate",          header: "expiryDate",         required: false, width: 18 },
    { key: "lastInspectionDate",  header: "lastInspectionDate", required: false, width: 20 },
    { key: "notes",               header: "notes",              required: false, width: 40 },
    { key: "assetId",             header: "assetId",            required: false, width: 30 },
  ],
  // ── Módulos export-only ──────────────────────────────────────────────────
  // Los headers no tienen "*" porque no se valida una columna como obligatoria
  // (no se importa). Las columnas que dejamos sirven solo de orden de export.
  crew: [
    { key: "crewCode",       header: "crewCode",       required: false, width: 16 },
    { key: "vesselCode",     header: "vesselCode",     required: false, width: 14 },
    { key: "firstName",      header: "firstName",      required: false, width: 18 },
    { key: "lastName",       header: "lastName",       required: false, width: 18 },
    { key: "rank",           header: "rank",           required: false, width: 18 },
    { key: "nationality",    header: "nationality",    required: false, width: 14 },
    { key: "dateOfBirth",    header: "dateOfBirth",    required: false, width: 14 },
    { key: "passportNumber", header: "passportNumber", required: false, width: 18 },
    { key: "signOnDate",     header: "signOnDate",     required: false, width: 14 },
    { key: "signOffDate",    header: "signOffDate",    required: false, width: 14 },
    { key: "status",         header: "status",         required: false, width: 14 },
    { key: "notes",          header: "notes",          required: false, width: 36 },
  ],
  crew_certifications: [
    { key: "crewCode",          header: "crewCode",          required: false, width: 16 },
    { key: "vesselCode",        header: "vesselCode",        required: false, width: 14 },
    { key: "crewFullName",      header: "crewFullName",      required: false, width: 28 },
    { key: "type",              header: "type",              required: false, width: 22 },
    { key: "certificateNumber", header: "certificateNumber", required: false, width: 22 },
    { key: "issuingAuthority",  header: "issuingAuthority",  required: false, width: 24 },
    { key: "issuedDate",        header: "issuedDate",        required: false, width: 14 },
    { key: "expiryDate",        header: "expiryDate",        required: false, width: 14 },
    { key: "status",            header: "status",            required: false, width: 16 },
    { key: "notes",             header: "notes",             required: false, width: 36 },
  ],
  crew_rest_hours: [
    { key: "crewCode",       header: "crewCode",       required: false, width: 16 },
    { key: "crewFullName",   header: "crewFullName",   required: false, width: 28 },
    { key: "vesselCode",     header: "vesselCode",     required: false, width: 14 },
    { key: "recordDate",     header: "recordDate",     required: false, width: 14 },
    { key: "totalRestHours", header: "totalRestHours", required: false, width: 16 },
    { key: "hasViolation",   header: "hasViolation",   required: false, width: 14 },
    { key: "violationsJson", header: "violations",     required: false, width: 36 },
    { key: "notes",          header: "notes",          required: false, width: 36 },
  ],
  drills: [
    { key: "drillCode",      header: "drillCode",      required: false, width: 18 },
    { key: "vesselCode",     header: "vesselCode",     required: false, width: 14 },
    { key: "type",           header: "type",           required: false, width: 22 },
    { key: "status",         header: "status",         required: false, width: 14 },
    { key: "scheduledDate",  header: "scheduledDate",  required: false, width: 16 },
    { key: "completedDate",  header: "completedDate",  required: false, width: 16 },
    { key: "scenario",       header: "scenario",       required: false, width: 36 },
    { key: "observations",   header: "observations",   required: false, width: 40 },
    { key: "lessonsLearned", header: "lessonsLearned", required: false, width: 40 },
  ],
  permits: [
    { key: "permitCode",        header: "permitCode",        required: false, width: 18 },
    { key: "vesselCode",        header: "vesselCode",        required: false, width: 14 },
    { key: "type",              header: "type",              required: false, width: 18 },
    { key: "status",            header: "status",            required: false, width: 14 },
    { key: "location",          header: "location",          required: false, width: 22 },
    { key: "description",       header: "description",       required: false, width: 40 },
    { key: "plannedStart",      header: "plannedStart",      required: false, width: 18 },
    { key: "plannedEnd",        header: "plannedEnd",        required: false, width: 18 },
    { key: "validFrom",         header: "validFrom",         required: false, width: 18 },
    { key: "validTo",           header: "validTo",           required: false, width: 18 },
    { key: "hazardsIdentified", header: "hazardsIdentified", required: false, width: 36 },
    { key: "controlMeasures",   header: "controlMeasures",   required: false, width: 36 },
    { key: "ppeRequired",       header: "ppeRequired",       required: false, width: 30 },
    { key: "alarmOverride",     header: "alarmOverride",     required: false, width: 14 },
    { key: "closeNotes",        header: "closeNotes",        required: false, width: 36 },
    { key: "rejectionReason",   header: "rejectionReason",   required: false, width: 28 },
  ],
  external_audits: [
    { key: "auditCode",         header: "auditCode",         required: false, width: 22 },
    { key: "vesselCode",        header: "vesselCode",        required: false, width: 14 },
    { key: "auditType",         header: "auditType",         required: false, width: 18 },
    { key: "auditDate",         header: "auditDate",         required: false, width: 14 },
    { key: "port",              header: "port",              required: false, width: 14 },
    { key: "country",           header: "country",           required: false, width: 14 },
    { key: "agencyOrAuthority", header: "agencyOrAuthority", required: false, width: 22 },
    { key: "inspectorName",     header: "inspectorName",     required: false, width: 22 },
    { key: "overallResult",     header: "overallResult",     required: false, width: 16 },
    { key: "summary",           header: "summary",           required: false, width: 40 },
    { key: "scoreOrRating",     header: "scoreOrRating",     required: false, width: 14 },
    { key: "reportUrl",         header: "reportUrl",         required: false, width: 30 },
    { key: "findingsCount",     header: "findingsCount",     required: false, width: 14 },
    { key: "findingsOpen",      header: "findingsOpen",      required: false, width: 14 },
  ],
  near_miss: [
    { key: "nearMissCode",      header: "nearMissCode",      required: false, width: 20 },
    { key: "vesselCode",        header: "vesselCode",        required: false, width: 14 },
    { key: "category",          header: "category",          required: false, width: 22 },
    { key: "severity",          header: "severity",          required: false, width: 14 },
    { key: "status",            header: "status",            required: false, width: 14 },
    { key: "occurredAt",        header: "occurredAt",        required: false, width: 18 },
    { key: "location",          header: "location",          required: false, width: 20 },
    { key: "description",       header: "description",       required: false, width: 40 },
    { key: "immediateAction",   header: "immediateAction",   required: false, width: 36 },
    { key: "rootCause",         header: "rootCause",         required: false, width: 36 },
    { key: "preventiveActions", header: "preventiveActions", required: false, width: 36 },
    { key: "lessonsLearned",    header: "lessonsLearned",    required: false, width: 36 },
    { key: "reportedByName",    header: "reportedByName",    required: false, width: 22 },
  ],
  moc: [
    { key: "mocCode",             header: "mocCode",             required: false, width: 20 },
    { key: "vesselCode",          header: "vesselCode",          required: false, width: 14 },
    { key: "category",            header: "category",            required: false, width: 22 },
    { key: "status",              header: "status",              required: false, width: 16 },
    { key: "riskLevel",           header: "riskLevel",           required: false, width: 12 },
    { key: "title",               header: "title",               required: false, width: 36 },
    { key: "reasonForChange",     header: "reasonForChange",     required: false, width: 40 },
    { key: "proposedChange",      header: "proposedChange",      required: false, width: 40 },
    { key: "riskAssessmentNotes", header: "riskAssessmentNotes", required: false, width: 40 },
    { key: "mitigationActions",   header: "mitigationActions",   required: false, width: 40 },
    { key: "plannedDate",         header: "plannedDate",         required: false, width: 14 },
    { key: "approvedAt",          header: "approvedAt",          required: false, width: 18 },
    { key: "approvedByName",      header: "approvedByName",      required: false, width: 22 },
    { key: "implementedAt",       header: "implementedAt",       required: false, width: 18 },
    { key: "implementedByName",   header: "implementedByName",   required: false, width: 22 },
    { key: "implementationNotes", header: "implementationNotes", required: false, width: 36 },
    { key: "reviewedAt",          header: "reviewedAt",          required: false, width: 18 },
    { key: "reviewOutcome",       header: "reviewOutcome",       required: false, width: 22 },
    { key: "reviewNotes",         header: "reviewNotes",         required: false, width: 36 },
    { key: "rejectedReason",      header: "rejectedReason",      required: false, width: 30 },
  ],
  spare_requests: [
    { key: "requestCode",            header: "requestCode",            required: false, width: 18 },
    { key: "status",                 header: "status",                 required: false, width: 14 },
    { key: "priority",               header: "priority",               required: false, width: 12 },
    { key: "requestedAt",            header: "requestedAt",            required: false, width: 16 },
    { key: "requestedForVesselCode", header: "requestedForVesselCode", required: false, width: 16 },
    { key: "itemsCount",             header: "itemsCount",             required: false, width: 12 },
    { key: "approvedAt",             header: "approvedAt",             required: false, width: 16 },
    { key: "rejectionReason",        header: "rejectionReason",        required: false, width: 30 },
    { key: "notes",                  header: "notes",                  required: false, width: 36 },
  ],
  fluid_samples: [
    { key: "sampleCode",       header: "sampleCode",       required: false, width: 18 },
    { key: "vesselCode",       header: "vesselCode",       required: false, width: 14 },
    { key: "assetId",          header: "assetId",          required: false, width: 26 },
    { key: "kind",             header: "kind",             required: false, width: 14 },
    { key: "fluidType",        header: "fluidType",        required: false, width: 16 },
    { key: "fluidProduct",     header: "fluidProduct",     required: false, width: 20 },
    { key: "sampledAt",        header: "sampledAt",        required: false, width: 16 },
    { key: "runningHours",     header: "runningHours",     required: false, width: 14 },
    { key: "containerCode",    header: "containerCode",    required: false, width: 16 },
    { key: "labName",          header: "labName",          required: false, width: 22 },
    { key: "labReference",     header: "labReference",     required: false, width: 18 },
    { key: "status",           header: "status",           required: false, width: 14 },
    { key: "resultVerdict",    header: "resultVerdict",    required: false, width: 16 },
    { key: "resultReceivedAt", header: "resultReceivedAt", required: false, width: 18 },
    { key: "resultSummary",    header: "resultSummary",    required: false, width: 40 },
  ],
  capa: [
    { key: "capaCode",        header: "capaCode",        required: false, width: 18 },
    { key: "vesselCode",      header: "vesselCode",      required: false, width: 14 },
    { key: "sourceType",      header: "sourceType",      required: false, width: 14 },
    { key: "status",          header: "status",          required: false, width: 18 },
    { key: "priority",        header: "priority",        required: false, width: 12 },
    { key: "title",           header: "title",           required: false, width: 36 },
    { key: "description",     header: "description",     required: false, width: 40 },
    { key: "owner",           header: "owner",           required: false, width: 22 },
    { key: "dueDate",         header: "dueDate",         required: false, width: 14 },
    { key: "completedAt",     header: "completedAt",     required: false, width: 16 },
    { key: "actionsTaken",    header: "actionsTaken",    required: false, width: 40 },
    { key: "verificationNote",       header: "verificationNote",      required: false, width: 36 },
    { key: "effectivenessCriteria",  header: "effectivenessCriteria", required: false, width: 36 },
    { key: "effectivenessReviewDate",header: "effectivenessReviewDate", required: false, width: 16 },
    { key: "effectivenessOutcome",   header: "effectivenessOutcome",  required: false, width: 16 },
  ],
  deferrals: [
    { key: "deferralCode",         header: "deferralCode",         required: false, width: 18 },
    { key: "vesselCode",           header: "vesselCode",           required: false, width: 14 },
    { key: "assetId",              header: "assetId",              required: false, width: 26 },
    { key: "sourceType",           header: "sourceType",           required: false, width: 16 },
    { key: "deferralType",         header: "deferralType",         required: false, width: 16 },
    { key: "status",               header: "status",               required: false, width: 14 },
    { key: "requestedAt",          header: "requestedAt",          required: false, width: 16 },
    { key: "targetDate",           header: "targetDate",           required: false, width: 14 },
    { key: "targetPort",           header: "targetPort",           required: false, width: 16 },
    { key: "justification",        header: "justification",        required: false, width: 40 },
    { key: "compensatoryMeasures", header: "compensatoryMeasures", required: false, width: 40 },
    { key: "decisionAt",           header: "decisionAt",           required: false, width: 16 },
    { key: "approverName",         header: "approverName",         required: false, width: 22 },
    { key: "activeSince",          header: "activeSince",          required: false, width: 16 },
    { key: "closedAt",             header: "closedAt",             required: false, width: 16 },
    { key: "closeNotes",           header: "closeNotes",           required: false, width: 36 },
    { key: "rejectionReason",      header: "rejectionReason",      required: false, width: 30 },
  ],
  defects: [
    { key: "defectCode",        header: "defectCode",        required: false, width: 18 },
    { key: "vesselCode",        header: "vesselCode",        required: false, width: 14 },
    { key: "assetId",           header: "assetId",           required: false, width: 26 },
    { key: "status",            header: "status",            required: false, width: 14 },
    { key: "severity",          header: "severity",          required: false, width: 12 },
    { key: "operationalState",  header: "operationalState",  required: false, width: 16 },
    { key: "classification",    header: "classification",    required: false, width: 24 },
    { key: "reportedAt",        header: "reportedAt",        required: false, width: 16 },
    { key: "description",       header: "description",       required: false, width: 40 },
    { key: "immediateAction",   header: "immediateAction",   required: false, width: 36 },
    { key: "correctiveAction",  header: "correctiveAction",  required: false, width: 36 },
    { key: "rcaMethodology",    header: "rcaMethodology",    required: false, width: 16 },
    { key: "rcaRootCause",      header: "rcaRootCause",      required: false, width: 36 },
    { key: "rcaCompletedAt",    header: "rcaCompletedAt",    required: false, width: 16 },
    { key: "capaDescription",   header: "capaDescription",   required: false, width: 36 },
    { key: "repairType",        header: "repairType",        required: false, width: 16 },
  ],
  daily_reports: [
    { key: "reportCode",             header: "reportCode",             required: false, width: 18 },
    { key: "vesselCode",             header: "vesselCode",             required: false, width: 14 },
    { key: "reportDate",             header: "reportDate",             required: false, width: 14 },
    { key: "status",                 header: "status",                 required: false, width: 14 },
    { key: "reportType",             header: "reportType",             required: false, width: 16 },
    { key: "operationalStatus",      header: "operationalStatus",      required: false, width: 18 },
    { key: "currentPort",            header: "currentPort",            required: false, width: 16 },
    { key: "nextPort",               header: "nextPort",               required: false, width: 16 },
    { key: "etaNextPort",            header: "etaNextPort",            required: false, width: 16 },
    { key: "etdNextPort",            header: "etdNextPort",            required: false, width: 16 },
    { key: "portCallType",           header: "portCallType",           required: false, width: 16 },
    { key: "positionLat",            header: "positionLat",            required: false, width: 14 },
    { key: "positionLon",            header: "positionLon",            required: false, width: 14 },
    { key: "engineHoursMain",        header: "engineHoursMain",        required: false, width: 16 },
    { key: "generatorHours",         header: "generatorHours",         required: false, width: 14 },
    { key: "fuelConsumedLiters",     header: "fuelConsumedLiters",     required: false, width: 18 },
    { key: "oilConsumedLiters",      header: "oilConsumedLiters",      required: false, width: 16 },
    { key: "estimatedStayHours",     header: "estimatedStayHours",     required: false, width: 16 },
    { key: "maintenanceOpportunity", header: "maintenanceOpportunity", required: false, width: 16 },
    { key: "sparesReceiptPossible",  header: "sparesReceiptPossible",  required: false, width: 16 },
    { key: "operationalRemarks",     header: "operationalRemarks",     required: false, width: 36 },
    { key: "summary",                header: "summary",                required: false, width: 40 },
    { key: "notes",                  header: "notes",                  required: false, width: 36 },
    { key: "verifiedAt",             header: "verifiedAt",             required: false, width: 16 },
    { key: "integratedAt",           header: "integratedAt",           required: false, width: 16 },
  ],
  monthly_reports: [
    { key: "vesselCode",        header: "vesselCode",        required: false, width: 14 },
    { key: "reportYear",        header: "reportYear",        required: false, width: 12 },
    { key: "reportMonth",       header: "reportMonth",       required: false, width: 12 },
    { key: "status",            header: "status",            required: false, width: 14 },
    { key: "operationalStatus", header: "operationalStatus", required: false, width: 18 },
    { key: "currentPort",       header: "currentPort",       required: false, width: 16 },
    { key: "nextPort",          header: "nextPort",          required: false, width: 16 },
    { key: "etaNextPort",       header: "etaNextPort",       required: false, width: 16 },
    { key: "positionLat",       header: "positionLat",       required: false, width: 14 },
    { key: "positionLon",       header: "positionLon",       required: false, width: 14 },
    { key: "summary",           header: "summary",           required: false, width: 50 },
    { key: "notes",             header: "notes",             required: false, width: 50 },
    { key: "submittedAt",       header: "submittedAt",       required: false, width: 16 },
    { key: "integratedAt",      header: "integratedAt",      required: false, width: 16 },
  ],
};

export function getModuleColumns(module: ExcelModule): ColumnDef[] {
  return MODULE_COLUMNS[module];
}

export async function generateTemplate(module: ExcelModule): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "CMS3.0";
  workbook.created = new Date();

  const sheet = workbook.addWorksheet(module);
  const cols = MODULE_COLUMNS[module];

  sheet.columns = cols.map((c) => ({
    key:   c.key,
    header: c.header,
    width: c.width ?? 20,
  }));

  // Bold header row
  const headerRow = sheet.getRow(1);
  headerRow.font = { bold: true };
  headerRow.fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: "FFE8E8E8" },
  };
  headerRow.commit();

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}
